# Generated by Django 2.0.3 on 2018-03-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientID1', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientR1', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientID2', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientR2', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientID3', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientR3', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientID4', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientR4', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientID5', models.DecimalField(decimal_places=0, max_digits=5)),
                ('clientR5', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerID1', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerR1', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerID2', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerR2', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerID3', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerR3', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerID4', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerR4', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerID5', models.DecimalField(decimal_places=0, max_digits=5)),
                ('workerR5', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
